template: |
  文本分类任务流程：

  1. 特征分析
     - 识别文本关键特征
     - 提取分类相关线索
     - 分析文本结构和模式

  2. 分类判断
     - 匹配分类标准
     - 评估分类依据
     - 确定分类结果
     - 计算置信度

  3. 结果验证
     - 检查分类准确性
     - 验证分类依据
     - 确认分类结果
     - 提供分类理由

  待分类文本：
  {{ content }}

  分类标准：
  {{ criteria }}

  分类选项：
  {{ categories }}

  {{ domain_knowledge }}
type: TaskPrompt
task_type: 文本分类
steps:
  - 特征分析
  - 分类判断
  - 结果验证
desc: "文本分类任务模板，适用于需要将文本归类到预定义类别的场景"
version: "1.0.0" 