template: |
  问题解决任务流程：

  1. 问题分析
     - 理解问题背景和需求
     - 识别关键问题和约束条件
     - 确定问题类型和解决方向

  2. 方案设计
     - 提出可能的解决方案
     - 评估方案的可行性和优缺点
     - 选择最优解决方案

  3. 实施步骤
     - 制定详细的实施计划
     - 准备必要的资源和工具
     - 按步骤执行解决方案

  4. 验证和优化
     - 验证解决方案的效果
     - 收集反馈并进行优化
     - 总结经验和教训

  {{ domain_knowledge }}
type: TaskPrompt
task_type: 问题解决
steps:
  - 问题分析
  - 方案设计
  - 实施步骤
  - 验证和优化
desc: "问题解决任务模板，适用于需要系统性思考和解决方案的场景"
version: "1.0.0" 